[tool.poetry]
name = "hon_patch_notes_game_bot"
version = "0.1.0"
description = ""
authors = ["William Lam <w.lam@honteam.com>"]

[tool.poetry.dependencies]
python = "^3.8"
praw = "^7.1.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pytest = "^6.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
