[tool.poetry]
name = "hon-patch-notes-game-bot"
version = "0.1.0"
description = ""
authors = ["William Lam <w.lam@honteam.com>"]

[tool.poetry.dependencies]
python = "^3.8"
praw = "^7.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
